### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by fedegiust** [gaganpreet/udemy-dl#28]
Hi,

I'm using OS X Yosemite and have Python 2.7.6 installed

When trying to install the script using 

sudo curl https://bootstrap.pypa.io/get-pip.py | python

It downloads and when trying to install I get this error

Exception:
  Traceback (most recent call last):
    File "/var/folders/19/_xp933014cq5sx6sn2bb_4pm0000gn/T/tmpFPAhPe/pip.zip/pip/basecommand.py", line 215, in main
      status = self.run(options, args)
    File "/var/folders/19/_xp933014cq5sx6sn2bb_4pm0000gn/T/tmpFPAhPe/pip.zip/pip/commands/install.py", line 347, in run
      root=options.root_path,
    File "/var/folders/19/_xp933014cq5sx6sn2bb_4pm0000gn/T/tmpFPAhPe/pip.zip/pip/req/req_set.py", line 548, in install
      **kwargs
    File "/var/folders/19/_xp933014cq5sx6sn2bb_4pm0000gn/T/tmpFPAhPe/pip.zip/pip/req/req_install.py", line 751, in install
      self.move_wheel_files(self.source_dir, root=root)
    File "/var/folders/19/_xp933014cq5sx6sn2bb_4pm0000gn/T/tmpFPAhPe/pip.zip/pip/req/req_install.py", line 960, in move_wheel_files
      isolated=self.isolated,
    File "/var/folders/19/_xp933014cq5sx6sn2bb_4pm0000gn/T/tmpFPAhPe/pip.zip/pip/wheel.py", line 234, in move_wheel_files
      clobber(source, lib_dir, True)
    File "/var/folders/19/_xp933014cq5sx6sn2bb_4pm0000gn/T/tmpFPAhPe/pip.zip/pip/wheel.py", line 205, in clobber
      os.makedirs(destdir)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
      mkdir(name, mode)
  OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/pip'

**Comment by fedegiust** [comment]
Sorry the error was when trying to install pip not your script.

I downloaded get-pip.py (https://bootstrap.pypa.io/get-pip.py) 
from http://pip.readthedocs.org/en/latest/installing.html

Then run

sudo python get-pip.py

I was then able to install your script without an issue
