### ISSUE TITLE
Issue with downloading

### ISSUE THREAD

**Issue by shafpatel** [gaganpreet/udemy-dl#42]
Using Windows 7 x64:
Installed udemy-dl with Pip.
Opening CMD, navigating to c:\Python34\lib\site-packages\udemy_dl
Typing udemy_dl.py gives this error:

c:\Python34\Lib\site-packages\udemy_dl>udemy_dl.py
Traceback (most recent call last):
  File "C:\Python34\Lib\site-packages\udemy_dl\udemy_dl.py", line 38, in <module
>

  File "C:\Python34\Lib\site-packages\udemy_dl\udemy_dl.py", line 25, in __init_
_

NameError: name 'requests' is not defined

c:\Python34\Lib\site-packages\udemy_dl>

**Comment by jeancx** [comment]
+1

**Comment by gaganpreet** [comment]
The steps mentioned in #60 should help.
