### ISSUE TITLE
Cannot download lecture

### ISSUE THREAD

**Issue by dma1979** [gaganpreet/udemy-dl#49]
I have used your application many times and it worked perfect.
But for one course I got a strange error by trying this course:
https://www.udemy.com/deploying-angularjs/

Full stack:
c:\Python34\Scripts>python https://www.udemy.com/deploying-angularjs
Downloading to: c:\Python34\Scripts\deploying-angularjs

Cannot download lecture "Technical Requirements"
Cannot download lecture "Scaffolding of the Project"
Cannot download lecture "A Sneak Peek of the Final Application"
Cannot download lecture "Building the BrowserSync and SASS Workflow"
Cannot download lecture "The Animals Service"
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\udemy_dl\udemy_dl.py", line 107, in get_vi
deo_links
    video_url = parse_video_url(lecture_id, hd)
  File "C:\Python34\lib\site-packages\udemy_dl\udemy_dl.py", line 71, in parse_v
ideo_url
    re.MULTILINE | re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "udemy-dl", line 5, in <module>
    main()
  File "C:\Python34\lib\site-packages\udemy_dl\udemy_dl.py", line 194, in main
    udemy_dl(username, password, link, output_dir)
  File "C:\Python34\lib\site-packages\udemy_dl\udemy_dl.py", line 148, in udemy_
dl
    for video in get_video_links(course_id, hd=True):
  File "C:\Python34\lib\site-packages\udemy_dl\udemy_dl.py", line 114, in get_vi
deo_links
    print('Cannot download lecture "%s"' % (lecture))
  File "C:\Python34\lib\encodings\cp866.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2019' in position
47: character maps to <undefined>

Hope you can resolve it.

**Comment by CryptXor** [comment]
Having a very similar issue.

**Comment by Agnusmag** [comment]
I am having the same problem

**Comment by shtml** [comment]
I found this problem

**Comment by titantelo15** [comment]
I have the same problem :(

**Comment by rinodung** [comment]
This may be a bug, when it can not get correct video url(from flashplayer)? Waiting for fixing...
