### ISSUE TITLE
Multiple line Errors

### ISSUE THREAD

**Issue by PaulMellor** [gaganpreet/udemy-dl#62]
Have been trying to get this to work but getting the following errors.
Have checked the Python (2.7) build, Currently running this on OS X and hoping it would work but comes up with the following output. sorry but this is still new to me but am trying. Any assistance would be great.

have installed via pip: youtube_dl, beautiful soup just to be sure nil dependencys missing.
"
Pauls-Mac-Pro-3:~ paulmellor$ sudo udemy-dl https:https://www.udemy.com/build-a-trivia-iphone-game-that-monetizes-swift-and-ios-8
Password:
Username/Email: p******@*********m	   
Password: 
Downloading to: /Users/paulmellor/build-a-trivia-iphone-game-that-monetizes-swift-and-ios-8

Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 5, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 195, in main
    udemy_dl(username, password, link, output_dir)
  File "/usr/local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 144, in udemy_dl
    course_id = get_course_id(course_link)
  File "/usr/local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 61, in get_course_id
    response = session.get(course_link)
  File "/usr/local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 29, in get
    return self.session.get(url, headers=self.headers)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 567, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 641, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'https:https://www.udemy.com/build-a-trivia-iphone-game-that-monetizes-swift-and-ios-8'
"

**Comment by PaulMellor** [comment]
Sorry seen my F$%K up. fixed
