### ISSUE TITLE
  InsecurePlatformWarning  - Any idea how to solve it? In addition, it stops downloading once several videos are downloaded

### ISSUE THREAD

**Issue by valizada** [gaganpreet/udemy-dl#73]
/Library/Python/2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by msj2** [comment]
I too faced the same issue.
Adding to the above issue:

I'm on Python 2.7.6



/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 5, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 195, in main
    udemy_dl(username, password, link, output_dir)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 142, in udemy_dl
    login(username, password)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 45, in login
    csrf_token = get_csrf_token()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 41, in get_csrf_token
    return match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'


I doubted it is issue with pip.
pip -freeze showed 

"I was using pip version 7.0.1, however version 7.1.0 is available"

Update to the new version of pip 7.1.0, using the command,
sudo pip install --upgrade pip
Tried downloading Udemy course, but didn't help.

Reading https://urllib3.readthedocs.org/en/latest/security.html#insecurerequestwarning, 

I did the below in the command prompt.

1) sudo apt-get install ndg-httpsclient

2)  sudo pip install certifi

3)  sudo pip install pyopenssl ndg-httpsclient pyasn1

Now, tried downloading udemy course.


It still failed, but without InsecurePlatform Warning

"Downloading to: /home/ferrari/udemy/<Course-Name>

Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 5, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 195, in main
    udemy_dl(username, password, link, output_dir)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 142, in udemy_dl
    login(username, password)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 45, in login
    csrf_token = get_csrf_token()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 41, in get_csrf_token
    return match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
"

So, after installing 3 pythonpackages, Issue looks to be in the group attribute.

**Comment by nishad** [comment]
@msj2 now your issue is https://github.com/gaganpreet/udemy-dl/issues/75

This is already resolved for the timebeing

**Comment by AlonFabula** [comment]
Getting the same error as @valizada.
