### ISSUE TITLE
Error when executing the script in OS X yosemite

### ISSUE THREAD

**Issue by Arduingo** [gaganpreet/udemy-dl#85]
Hi,

After run de command udemy-dl URL in the command line in Yosemite, using a tested login/pass I get this error

Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 5, in <module>
    main()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 215, in main
    udemy_dl(username, password, link, output_dir)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 162, in udemy_dl
    login(username, password)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 51, in login
    csrf_token = get_csrf_token()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 46, in get_csrf_token
    return soup.find_all('input', {'name': 'csrf'})[0]['value']
IndexError: list index out of range

Whats could be wrong?

**Comment by nishad** [comment]
Please update your udemy-dl. You are using an older version of the script or Pacakge.

**Comment by Arduingo** [comment]
Thanks! fixed after run pip install --upgrade udemy-dl
